layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji
  - jekyll-paginate

permalink: /:year/:month/:day/:title/

sass:
  sass_dir: assets/css/
  load_paths:
    - node_modules/
    - _sass/

defaults:
  -
    scope:
      path: "_posts/" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 12
  exclude:
    archived: true
    forks: true
    projects:
    - svrooij.github.io
    - node-sonos
    - svrooij

social_media:
  twitter: svrooij
  website: https://svrooij.io
  linkedin: stephanvanrooij
  stackoverflow: 639153
  # behance: your_username
  # dribbble: your_username
  facebook: svrooij
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  
  # mastodon: your_username
  # medium: your_username
  
  # telegram: your_username
  
  # unsplash: your_username
  # vk: your_username
  
  # youtube: your_username

topics:
  - name: Home Automation
    web_url: https://github.com/topics/homeautomation

  - name: MQTT
    web_url: https://github.com/topics/mqtt

  - name: ESP8266
    web_url: https://github.com/topics/esp8266

paginate: 4

avatar_url: /assets/my-github-picture.png

excerpt_separator: <!--more-->
